# Generated by Django 2.0.4 on 2020-04-05 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filemanagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Files',
        ),
    ]
