# Generated by Django 2.0.4 on 2020-04-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filelabel', models.CharField(max_length=255, null=True)),
                ('userid', models.IntegerField()),
                ('ruleid', models.IntegerField()),
            ],
        ),
    ]
