# Generated by Django 2.0.4 on 2020-04-27 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filelogs',
            name='uploadid',
        ),
        migrations.RemoveField(
            model_name='files',
            name='user',
        ),
        migrations.DeleteModel(
            name='FilesData',
        ),
        migrations.DeleteModel(
            name='Rules',
        ),
        migrations.DeleteModel(
            name='FileLogs',
        ),
        migrations.DeleteModel(
            name='Files',
        ),
    ]
