# Generated by Django 2.0.4 on 2020-04-18 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_filemetadata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileMetaData',
            new_name='FilesData',
        ),
    ]
