# Generated by Django 2.0.4 on 2020-04-05 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200405_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='created_by',
            new_name='user',
        ),
    ]
