# Generated by Django 2.0.4 on 2020-04-06 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200405_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='create_dte',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
