# Generated by Django 2.0.4 on 2020-05-20 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200427_1354'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rules',
        ),
    ]
