# Generated by Django 2.0.4 on 2020-04-10 05:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200406_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logs', models.CharField(default='TEST', max_length=250)),
                ('create_dte', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.RenameField(
            model_name='files',
            old_name='fileid',
            new_name='uploadid',
        ),
        migrations.AddField(
            model_name='filelogs',
            name='files',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_name', to='account.Files'),
        ),
        migrations.AddField(
            model_name='filelogs',
            name='uploadid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_id', to='account.Files'),
        ),
    ]
