# Generated by Django 2.0.4 on 2020-05-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_delete_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('ruleid', models.AutoField(primary_key=True, serialize=False)),
                ('rule', models.TextField()),
                ('rulemodule', models.TextField()),
                ('isactive', models.BooleanField(default=True)),
            ],
        ),
    ]
