# Generated by Django 2.0.4 on 2020-04-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200410_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filelogs',
            name='files',
            field=models.CharField(max_length=250),
        ),
    ]
