# Generated by Django 3.0.4 on 2020-04-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200410_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filelogs',
            name='logs',
            field=models.CharField(default='TEST1', max_length=250),
        ),
    ]
