# Generated by Django 2.0.4 on 2020-04-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200410_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesData',
            fields=[
                ('fileid', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=30)),
                ('userid', models.IntegerField()),
                ('ruleid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('ruleid', models.AutoField(primary_key=True, serialize=False)),
                ('rule', models.CharField(max_length=255)),
            ],
        ),
    ]
