# Generated by Django 2.0.4 on 2020-04-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_filesdata_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='rule',
            field=models.TextField(),
        ),
    ]
