# Generated by Django 2.0.4 on 2020-04-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200411_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesdata',
            name='filename',
            field=models.CharField(max_length=255),
        ),
    ]
