# Generated by Django 3.0.4 on 2020-04-11 11:27

import account.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20200411_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='files',
            field=models.FileField(storage=account.storage.CustomFileSystemStorage, upload_to='files/'),
        ),
    ]
