# Generated by Django 2.0.4 on 2020-04-12 07:09

import account.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200411_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='files',
            field=models.FileField(storage=account.storage.CustomFileSystemStorage(), upload_to='files/'),
        ),
    ]
